version: "3.0"
services:
  bookfront:
    image: bookfront
    ports:
      - 3000:3000
    volumes:
      - ./bookFront/src:/app/src # bind mount
    environment:
      BOOK_HOST: bookhost
      BACKEND: bookback
      TIMEOUT: 10
    # networks:
    #   shared:
    #     ipv4_address: 172.168.10.23

  bookback:
    image: bookback
    volumes:
      - ./bookBack/src:/app/src # bind mount
    deploy:
      replicas: 1
    ports:
      - 3001:3001
    environment:
      BOOK_HOST: bookhost

  bookhost:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose:
      - "27017"
    volumes:
      - booktracker-data:/data/db
      - mongo-config:/data/configdb

volumes:
  booktracker-data:
  mongo-config: